import os
os.makedirs("C:/Users/lenovo/hwin_net/utils", exist_ok=True)

lines = []

# Header
lines.append("\"\"\"")
lines.append("HWIN-Net Configuration Module")
lines.append("")
lines.append("Mathematical Purpose")
lines.append("--------------------")
lines.append("This module defines the complete configuration schema for HWIN-Net, ensuring")
lines.append("theorem-to-configuration traceability per the frozen SIS theory (SIS_Reaxiomatized.md)")
lines.append("and the canonical implementation specification (HWIN_Net_Spec.md).")
lines.append("\"\"\"")
lines.append("")

# Imports
lines.append("from dataclasses import dataclass, field")
lines.append("from typing import List, Optional, Dict, Any, Tuple, Literal")
lines.append("from pathlib import Path")
lines.append("import yaml")
lines.append("from omegaconf import OmegaConf, DictConfig")
lines.append("import hydra")
lines.append("from hydra.core.config_store import ConfigStore")
lines.append("")

# Module 1: EncoderConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# MODULE 1: SCHEMA ENCODER (M1) -- Axiom A2, A3, D2, Section 5.1")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class EncoderConfig:")
lines.append("    encoder_type = field(default=\"mlp\", metadata={\"theorem_ref\": \"A2, A3, D2\", \"description\": \"Architecture of platform-specific encoder f_a\"})")
lines.append("    n_layers = field(default=3, metadata={\"theorem_ref\": \"A2, A3\", \"description\": \"Number of hidden layers in f_a\"})")
lines.append("    hidden_dim = field(default=128, metadata={\"theorem_ref\": \"A2, A3\", \"description\": \"Hidden dimension of f_a\"})")
lines.append("    output_dim = field(default=128, metadata={\"theorem_ref\": \"D2\", \"description\": \"Output dimension k of encoder f_a: R^n -> R^k\"})")
lines.append("    platform_embedding_dim = field(default=32, metadata={\"theorem_ref\": \"A2, A3\", \"description\": \"Platform embedding dimension k_a\"})")
lines.append("    num_platforms = field(default=3, metadata={\"theorem_ref\": \"A2, A3\", \"description\": \"Number of platforms |A|\"})")
lines.append("    share_platform_encoder = field(default=False, metadata={\"theorem_ref\": \"A2, A3\", \"description\": \"Share encoder weights across platforms\"})")
lines.append("    mask_mode = field(default=\"zero_fill\", metadata={\"theorem_ref\": \"D2\", \"description\": \"How to mask unobserved dimensions\"})")
lines.append("    dropout = field(default=0.1, metadata={\"theorem_ref\": \"impl\", \"description\": \"Dropout rate in encoder layers\"})")
lines.append("    activation = field(default=\"gelu\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Activation function\"})")
lines.append("    norm_type = field(default=\"layer\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Normalization type\"})")

# Module 2: RecoveryConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# MODULE 2: RECOVERY MODULE (M2) -- Axiom A4, Lemma 2, Lemma 5, CC3, Section 5.2")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class RecoveryConfig:")
lines.append("    recovery_type = field(default=\"equivariant_mlp\", metadata={\"theorem_ref\": \"A4, L2, L5\", \"description\": \"Architecture of T_{(O,a)}\"})")
lines.append("    latent_dim = field(default=64, metadata={\"theorem_ref\": \"A4, D5\", \"description\": \"Latent dimension d of mu: M -> R^d\"})")
lines.append("    hidden_dim = field(default=128, metadata={\"theorem_ref\": \"A4, L2\", \"description\": \"Hidden dimension of recovery network\"})")
lines.append("    n_layers = field(default=3, metadata={\"theorem_ref\": \"A4, L2\", \"description\": \"Number of layers in T_{(O,a)}\"})")
lines.append("    intertwiner_type = field(default=\"linear\", metadata={\"theorem_ref\": \"L5, CC3\", \"description\": \"Type of intertwiner R_{a2,a1} for weight tying\"})")
lines.append("    base_platform = field(default=0, metadata={\"theorem_ref\": \"L5\", \"description\": \"Reference platform a_ref for T_{(O,a)} = R_{a,a_ref} o T_{(O,a_ref)}\"})")
lines.append("    tie_t_base = field(default=True, metadata={\"theorem_ref\": \"CC3, L5\", \"description\": \"Share base T_{(O,a_ref)} across platforms\"})")
lines.append("    equivariance_loss_weight = field(default=1.0, metadata={\"theorem_ref\": \"L5, CC3\", \"description\": \"Weight for equivariance loss\"})")
lines.append("    dropout = field(default=0.1, metadata={\"theorem_ref\": \"impl\", \"description\": \"Dropout in recovery layers\"})")
lines.append("    activation = field(default=\"gelu\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Activation function\"})")
lines.append("    norm_type = field(default=\"layer\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Normalization type\"})")

# Module 3: RetractionConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# MODULE 3: MANIFOLD RETRACTION (M3) -- Axiom A1, Theorem 1, D12, CC4, Section 5.3")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class RetractionConfig:")
lines.append("    retraction_type = field(default=\"pca\", metadata={\"theorem_ref\": \"A1, T1, CC4, D12\", \"description\": \"Type of retraction rho: R^d -> mu(M)\"})")
lines.append("    latent_dim = field(default=64, metadata={\"theorem_ref\": \"A4, D5\", \"description\": \"Dimension d of latent space R^d\"})")
lines.append("    manifold_basis_path = field(default=None, metadata={\"theorem_ref\": \"D12, CC4\", \"description\": \"Path to precomputed basis of mu(M) for orthogonal projection\"})")
lines.append("    pca_components = field(default=32, metadata={\"theorem_ref\": \"D12\", \"description\": \"Number of PCA components for mu(M) subspace\"})")
lines.append("    vae_latent_dim = field(default=16, metadata={\"theorem_ref\": \"CC4\", \"description\": \"VAE bottleneck dimension for manifold learning\"})")
lines.append("    vae_encoder_layers = field(default_factory=lambda: [128, 64], metadata={\"theorem_ref\": \"CC4\", \"description\": \"VAE encoder hidden layers\"})")
lines.append("    vae_decoder_layers = field(default_factory=lambda: [64, 128], metadata={\"theorem_ref\": \"CC4\", \"description\": \"VAE decoder hidden layers\"})")
lines.append("    max_iter = field(default=10, metadata={\"theorem_ref\": \"CC4\", \"description\": \"Max iterations for iterative projection\"})")
lines.append("    tolerance = field(default=1e-6, metadata={\"theorem_ref\": \"CC4\", \"description\": \"Convergence tolerance for iterative projection\"})")
lines.append("    idempotence_loss_weight = field(default=1.0, metadata={\"theorem_ref\": \"CC4\", \"description\": \"Weight for idempotence loss\"})")

# Module 4: QueryHeadConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# MODULE 4: QUERY HEAD (M4) -- Axiom A5, Theorem 3, Lemma 8, Section 5.4")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class QueryHeadConfig:")
lines.append("    head_type = field(default=\"mlp\", metadata={\"theorem_ref\": \"A5, T3, L8\", \"description\": \"Architecture of psi': R^d -> Delta(Y)\"})")
lines.append("    latent_dim = field(default=64, metadata={\"theorem_ref\": \"D5\", \"description\": \"Input dimension d = dim(mu(M))\"})")
lines.append("    output_dim = field(default=1, metadata={\"theorem_ref\": \"P9, D6\", \"description\": \"Output dimension |Y| (target space)\"})")
lines.append("    hidden_dim = field(default=64, metadata={\"theorem_ref\": \"impl\", \"description\": \"Hidden dimension for MLP head\"})")
lines.append("    n_layers = field(default=2, metadata={\"theorem_ref\": \"impl\", \"description\": \"Number of layers in MLP head\"})")
lines.append("    output_distribution = field(default=\"gaussian\", metadata={\"theorem_ref\": \"T5\", \"description\": \"Output distribution type for aleatoric uncertainty sigma^2_aleat\"})")
lines.append("    dropout = field(default=0.1, metadata={\"theorem_ref\": \"impl\", \"description\": \"Dropout in query head\"})")
lines.append("    activation = field(default=\"gelu\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Activation function\"})")

# Module 5: GateConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# MODULE 5: IDENTIFIABILITY GATE / ROUTER (M5) -- Axiom A4, Theorem 4, Lemma 7, D11, D11b, CC2, T5")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class GateConfig:")
lines.append("    r0_method = field(default=\"lookup\", metadata={\"theorem_ref\": \"A4, CR-A4b\", \"description\": \"Method to compute r_0(g): lookup table, learned regressor, or C3 formula\"})")
lines.append("    r0_init = field(default=10.0, metadata={\"theorem_ref\": \"A4, L7\", \"description\": \"Initial value for r_0(g) thresholds\"})")
lines.append("    prior_predictive_type = field(default=\"empirical_bayes\", metadata={\"theorem_ref\": \"D11, D11b\", \"description\": \"Type of prior predictive p(q | nothing)\"})")
lines.append("    prior_mean = field(default=0.0, metadata={\"theorem_ref\": \"D11\", \"description\": \"Prior mean E[q] for non-ID schemas\"})")
lines.append("    prior_var = field(default=1.0, metadata={\"theorem_ref\": \"D11b\", \"description\": \"Prior variance Var[q] = sigma^2_nonid (constant across non-ID schemas D11b)\"})")
lines.append("    hard_gate = field(default=True, metadata={\"theorem_ref\": \"CC2, CR-CC2\", \"description\": \"Hard binary gate at |O| = r_0(g) (must be True per CC2)\"})")
lines.append("    schemas = field(default_factory=list, metadata={\"theorem_ref\": \"D1, A3\", \"description\": \"List of schemas (O, a) for r_0 lookup table\"})")
lines.append("    r0_regressor_hidden = field(default=64, metadata={\"theorem_ref\": \"impl\", \"description\": \"Hidden dim for r_0 regressor\"})")

# Module 6: NoLeakageConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# MODULE 6: NO-LEAKAGE REGULARIZER (M6) -- Axiom A5, CC5, C1, Section 5.6")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class NoLeakageConfig:")
lines.append("    mi_estimator = field(default=\"adversarial\", metadata={\"theorem_ref\": \"A5, CC5, C1\", \"description\": \"Mutual information estimation method\"})")
lines.append("    discriminator_type = field(default=\"mlp\", metadata={\"theorem_ref\": \"CC5\", \"description\": \"Discriminator D_theta architecture\"})")
lines.append("    discriminator_hidden = field(default=64, metadata={\"theorem_ref\": \"CC5\", \"description\": \"Hidden dimension of discriminator\"})")
lines.append("    discriminator_layers = field(default=2, metadata={\"theorem_ref\": \"CC5\", \"description\": \"Number of discriminator layers\"})")
lines.append("    gradient_reversal = field(default=True, metadata={\"theorem_ref\": \"A5, CC5\", \"description\": \"Use gradient reversal layer for adversarial MI\"})")
lines.append("    grl_lambda = field(default=1.0, metadata={\"theorem_ref\": \"A5, CC5\", \"description\": \"Gradient reversal lambda (can be scheduled)\"})")
lines.append("    lambda_mi = field(default=0.1, metadata={\"theorem_ref\": \"A5, CC5, C1\", \"description\": \"Weight lambda_MI for MI penalty in total loss (must be > 0)\"})")

# LossConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# LOSS CONFIGURATION -- 5 Loss Terms + Weights (Section 5.6, Training)")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class LossConfig:")
lines.append("    lambda_pred = field(default=1.0, metadata={\"theorem_ref\": \"A4, T3, T5\", \"description\": \"Weight for prediction loss L_pred\"})")
lines.append("    lambda_rec = field(default=1.0, metadata={\"theorem_ref\": \"CC1, A4\", \"description\": \"Weight for recovery loss L_rec\"})")
lines.append("    lambda_noleak = field(default=0.1, metadata={\"theorem_ref\": \"A5, CC5, C1\", \"description\": \"Weight for no-leakage MI loss L_noleak\"})")
lines.append("    lambda_equiv = field(default=0.1, metadata={\"theorem_ref\": \"L5, CC3\", \"description\": \"Weight for equivariance loss L_equiv\"})")
lines.append("    lambda_complex = field(default=1e-4, metadata={\"theorem_ref\": \"CC1\", \"description\": \"Weight for complexity penalty L_complex on mu\"})")
lines.append("    pred_loss_type = field(default=\"mse\", metadata={\"theorem_ref\": \"A4, T3, T5\", \"description\": \"Prediction loss function type\"})")
lines.append("    rec_loss_type = field(default=\"mse\", metadata={\"theorem_ref\": \"CC1\", \"description\": \"Recovery loss type: MSE or min-max\"})")
lines.append("    equiv_loss_type = field(default=\"frobenius\", metadata={\"theorem_ref\": \"L5, CC3\", \"description\": \"Equivariance loss: ||R_{a2,a1} - I||_F^2 or spectral norm\"})")

# TrainingConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# TRAINING CONFIGURATION -- TTUR, Gradient Reversal, Checkpointing (Training section)")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class TrainingConfig:")
lines.append("    max_epochs = field(default=100, metadata={\"theorem_ref\": \"impl\", \"description\": \"Maximum training epochs\"})")
lines.append("    batch_size = field(default=32, metadata={\"theorem_ref\": \"impl\", \"description\": \"Training batch size\"})")
lines.append("    val_batch_size = field(default=64, metadata={\"theorem_ref\": \"impl\", \"description\": \"Validation batch size\"})")
lines.append("    use_ttur = field(default=True, metadata={\"theorem_ref\": \"Training\", \"description\": \"Use two-time-scale update rule (TTUR)\"})")
lines.append("    lr_main = field(default=1e-3, metadata={\"theorem_ref\": \"Training\", \"description\": \"Learning rate for main parameters (theta, psi')\"})")
lines.append("    lr_recovery = field(default=5e-4, metadata={\"theorem_ref\": \"Training\", \"description\": \"Learning rate for recovery module T_g (theta_T)\"})")
lines.append("    lr_adversarial = field(default=2e-4, metadata={\"theorem_ref\": \"A5, CC5\", \"description\": \"Learning rate for adversarial discriminator\"})")
lines.append("    optimizer_type = field(default=\"adamw\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Optimizer type\"})")
lines.append("    weight_decay = field(default=1e-4, metadata={\"theorem_ref\": \"impl\", \"description\": \"Weight decay\"})")
lines.append("    beta1 = field(default=0.9, metadata={\"theorem_ref\": \"impl\", \"description\": \"Adam beta1\"})")
lines.append("    beta2 = field(default=0.999, metadata={\"theorem_ref\": \"impl\", \"description\": \"Adam beta2\"})")
lines.append("    eps = field(default=1e-8, metadata={\"theorem_ref\": \"impl\", \"description\": \"Adam epsilon\"})")
lines.append("    scheduler_type = field(default=\"cosine\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Learning rate scheduler\"})")
lines.append("    warmup_epochs = field(default=5, metadata={\"theorem_ref\": \"impl\", \"description\": \"Warmup epochs\"})")
lines.append("    min_lr = field(default=1e-6, metadata={\"theorem_ref\": \"impl\", \"description\": \"Minimum learning rate\"})")
lines.append("    step_size = field(default=30, metadata={\"theorem_ref\": \"impl\", \"description\": \"StepLR step size\"})")
lines.append("    gamma = field(default=0.1, metadata={\"theorem_ref\": \"impl\", \"description\": \"StepLR gamma\"})")
lines.append("    plateau_patience = field(default=10, metadata={\"theorem_ref\": \"impl\", \"description\": \"ReduceLROnPlateau patience\"})")
lines.append("    plateau_factor = field(default=0.5, metadata={\"theorem_ref\": \"impl\", \"description\": \"ReduceLROnPlateau factor\"})")
lines.append("    grad_clip_norm = field(default=1.0, metadata={\"theorem_ref\": \"impl\", \"description\": \"Max gradient norm for clipping\"})")
lines.append("    use_mixed_precision = field(default=True, metadata={\"theorem_ref\": \"Training\", \"description\": \"Use torch.cuda.amp autocast (Torch 2.x)\"})")
lines.append("    checkpoint_dir = field(default=\"./checkpoints\", metadata={\"theorem_ref\": \"Training\", \"description\": \"Checkpoint directory\"})")
lines.append("    save_every_n_epochs = field(default=10, metadata={\"theorem_ref\": \"Training\", \"description\": \"Save checkpoint every N epochs\"})")
lines.append("    keep_last_n_checkpoints = field(default=3, metadata={\"theorem_ref\": \"Training\", \"description\": \"Number of checkpoints to keep\"})")
lines.append("    resume_from = field(default=None, metadata={\"theorem_ref\": \"Training\", \"description\": \"Path to checkpoint to resume from\"})")
lines.append("    validate_every_n_epochs = field(default=1, metadata={\"theorem_ref\": \"Training\", \"description\": \"Run validation every N epochs\"})")
lines.append("    early_stopping_patience = field(default=20, metadata={\"theorem_ref\": \"Training\", \"description\": \"Early stopping patience\"})")
lines.append("    early_stopping_metric = field(default=\"val_loss\", metadata={\"theorem_ref\": \"Training\", \"description\": \"Metric for early stopping\"})")
lines.append("    early_stopping_mode = field(default=\"min\", metadata={\"theorem_ref\": \"Training\", \"description\": \"Early stopping mode\"})")
lines.append("    seed = field(default=42, metadata={\"theorem_ref\": \"Training\", \"description\": \"Random seed for reproducibility\"})")
lines.append("    deterministic = field(default=True, metadata={\"theorem_ref\": \"Training\", \"description\": \"Use deterministic algorithms (cuDNN)\"})")
lines.append("    device = field(default=\"auto\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Compute device\"})")
lines.append("    num_workers = field(default=4, metadata={\"theorem_ref\": \"impl\", \"description\": \"DataLoader workers\"})")
lines.append("    pin_memory = field(default=True, metadata={\"theorem_ref\": \"impl\", \"description\": \"Pin memory for DataLoader\"})")

# DataConfig
lines.append("")
lines.append("# ============================================================================")
lines.append("# DATA CONFIGURATION -- Schema-aware Dataset (Datasets section)")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class DataConfig:")
lines.append("    train_data_path = field(default=\"./data/train.parquet\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Training data path\"})")
lines.append("    val_data_path = field(default=\"./data/val.parquet\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Validation data path\"})")
lines.append("    test_data_path = field(default=\"./data/test.parquet\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Test data path\"})")
lines.append("    num_variables = field(default=100, metadata={\"theorem_ref\": \"D1, D2\", \"description\": \"Number of canonical variables |V| = n\"})")
lines.append("    schemas = field(default_factory=list, metadata={\"theorem_ref\": \"D1, A3\", \"description\": \"List of schemas (O, a) in dataset\"})")
lines.append("    schemas_file = field(default=None, metadata={\"theorem_ref\": \"D1\", \"description\": \"Path to schema definitions file (JSON/YAML)\"})")
lines.append("    platform_embeddings_file = field(default=None, metadata={\"theorem_ref\": \"A2, P5, P6\", \"description\": \"Path to platform embeddings e_a\"})")
lines.append("    num_platforms = field(default=3, metadata={\"theorem_ref\": \"A2, A3\", \"description\": \"Number of platforms |A|\"})")
lines.append("    target_column = field(default=\"y\", metadata={\"theorem_ref\": \"P9\", \"description\": \"Target column name\"})")
lines.append("    target_type = field(default=\"regression\", metadata={\"theorem_ref\": \"P9\", \"description\": \"Target type\"})")
lines.append("    schema_sampler_type = field(default=\"stratified\", metadata={\"theorem_ref\": \"Datasets\", \"description\": \"Schema sampling strategy\"})")
lines.append("    min_observed_vars = field(default=1, metadata={\"theorem_ref\": \"A4, L7\", \"description\": \"Minimum |O| for a valid sample\"})")
lines.append("    normalize_features = field(default=True, metadata={\"theorem_ref\": \"impl\", \"description\": \"Normalize input features x\"})")
lines.append("    feature_mean_path = field(default=None, metadata={\"theorem_ref\": \"impl\", \"description\": \"Path to feature mean for normalization\"})")
lines.append("    feature_std_path = field(default=None, metadata={\"theorem_ref\": \"impl\", \"description\": \"Path to feature std for normalization\"})")

# Root Config
lines.append("")
lines.append("# ============================================================================")
lines.append("# ROOT CONFIGURATION -- Composed Config")
lines.append("# ============================================================================")
lines.append("")
lines.append("@dataclass")
lines.append("class Config:")
lines.append("    encoder = field(default_factory=EncoderConfig)")
lines.append("    recovery = field(default_factory=RecoveryConfig)")
lines.append("    retraction = field(default_factory=RetractionConfig)")
lines.append("    query_head = field(default_factory=QueryHeadConfig)")
lines.append("    gate = field(default_factory=GateConfig)")
lines.append("    no_leakage = field(default_factory=NoLeakageConfig)")
lines.append("    loss = field(default_factory=LossConfig)")
lines.append("    training = field(default_factory=TrainingConfig)")
lines.append("    data = field(default_factory=DataConfig)")
lines.append("    experiment_name = field(default=\"hwin_net\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Experiment name for logging\"})")
lines.append("    output_dir = field(default=\"./outputs\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Output directory for logs/checkpoints\"})")
lines.append("    log_level = field(default=\"info\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Logging level\"})")
lines.append("    _target_ = field(default=\"models.hwin_net.HWINNet\", metadata={\"theorem_ref\": \"impl\", \"description\": \"Target class for Hydra instantiation\"})")

# Utility functions
lines.append("")
lines.append("# ============================================================================")
lines.append("# CONFIG LOADING / SAVING UTILITIES")
lines.append("# ============================================================================")
lines.append("")
lines.append("def load_config(config_path=None, overrides=None):")
lines.append("    if config_path is not None:")
lines.append("        with open(config_path, \"r\") as f:")
lines.append("            yaml_config = yaml.safe_load(f)")
lines.append("        cfg = OmegaConf.structured(Config)")
lines.append("        cfg = OmegaConf.merge(cfg, yaml_config)")
lines.append("    else:")
lines.append("        cfg = OmegaConf.structured(Config)")
lines.append("    if overrides:")
lines.append("        override_conf = OmegaConf.from_dotlist(overrides)")
lines.append("        cfg = OmegaConf.merge(cfg, override_conf)")
lines.append("    config = OmegaConf.to_object(cfg)")
lines.append("    return config")
lines.append("")
lines.append("def save_config(config, output_path):")
lines.append("    cfg = OmegaConf.structured(config)")
lines.append("    OmegaConf.save(cfg, output_path)")
lines.append("")
lines.append("def create_config_store():")
lines.append("    cs = ConfigStore.instance()")
lines.append("    cs.store(name=\"config\", node=Config)")
lines.append("    return cs")
lines.append("")
lines.append("def validate_config(config):")
lines.append("    errors = []")
lines.append("    if not config.gate.hard_gate:")
lines.append("        errors.append(\"THEOREM VIOLATION: gate.hard_gate must be True (CC2 requires hard binary gate)\")")
lines.append("    if config.no_leakage.lambda_mi <= 0:")
lines.append("        errors.append(\"THEOREM VIOLATION: no_leakage.lambda_mi must be > 0 (A5, CC5, C1)\")")
lines.append("    if not config.recovery.tie_t_base:")
lines.append("        errors.append(\"WARNING: recovery.tie_t_base=False violates CC3 weight-tying requirement\")")
lines.append("    if config.encoder.output_dim != config.recovery.hidden_dim:")
lines.append("        errors.append(f\"DIMENSION MISMATCH: encoder.output_dim ({config.encoder.output_dim}) != recovery.hidden_dim ({config.recovery.hidden_dim})\")")
lines.append("    if config.recovery.latent_dim != config.query_head.latent_dim:")
lines.append("        errors.append(f\"DIMENSION MISMATCH: recovery.latent_dim ({config.recovery.latent_dim}) != query_head.latent_dim ({config.query_head.latent_dim})\")")
lines.append("    if config.recovery.latent_dim != config.retraction.latent_dim:")
lines.append("        errors.append(f\"DIMENSION MISMATCH: recovery.latent_dim ({config.recovery.latent_dim}) != retraction.latent_dim ({config.retraction.latent_dim})\")")
lines.append("    if config.query_head.latent_dim != config.retraction.latent_dim:")
lines.append("        errors.append(f\"DIMENSION MISMATCH: query_head.latent_dim ({config.query_head.latent_dim}) != retraction.latent_dim ({config.retraction.latent_dim})\")")
lines.append("    if config.encoder.num_platforms < config.recovery.base_platform + 1:")
lines.append("        errors.append(f\"WARNING: encoder.num_platforms ({config.encoder.num_platforms}) should be >= recovery.base_platform+1 ({config.recovery.base_platform+1})\")")
lines.append("    return errors")
lines.append("")
lines.append("def get_default_config():")
lines.append("    return Config()")
lines.append("")

# Main test
lines.append("if __name__ == \"__main__\":")
lines.append("    cfg = get_default_config()")
lines.append("    print(\"Default config loaded successfully\")")
lines.append("    print(f\"Experiment: {cfg.experiment_name}\")")
lines.append("    print(f\"Encoder: {cfg.encoder.encoder_type}, dim={cfg.encoder.output_dim}\")")
lines.append("    print(f\"Recovery: {cfg.recovery.recovery_type}, latent_dim={cfg.recovery.latent_dim}\")")
lines.append("    print(f\"Retraction: {cfg.retraction.retraction_type}\")")
lines.append("    print(f\"Query Head: {cfg.query_head.head_type}\")")
lines.append("    print(f\"Gate: r0_method={cfg.gate.r0_method}, hard_gate={cfg.gate.hard_gate}\")")
lines.append("    print(f\"NoLeakage: {cfg.no_leakage.mi_estimator}, lambda_mi={cfg.no_leakage.lambda_mi}\")")
lines.append("    print(f\"Loss weights: pred={cfg.loss.lambda_pred}, rec={cfg.loss.lambda_rec}, noleak={cfg.loss.lambda_noleak}, equiv={cfg.loss.lambda_equiv}, complex={cfg.loss.lambda_complex}\")")
lines.append("    print(f\"Training: TTUR={cfg.training.use_ttur}, max_epochs={cfg.training.max_epochs}\")")
lines.append("    errors = validate_config(cfg)")
lines.append("    if errors:")
lines.append("        print(\"\\nVALIDATION ERRORS:\")")
lines.append("        for e in errors:")
lines.append("            print(f\"  - {e}\")")
lines.append("    else:")
lines.append("        print(\"\\nConfig validation PASSED\")")
lines.append("    import tempfile")
lines.append("    with tempfile.NamedTemporaryFile(mode=\"w\", suffix=\".yaml\", delete=False) as f:")
lines.append("        save_config(cfg, f.name)")
lines.append("        print(f\"\\nSaved config to {f.name}\")")
lines.append("        cfg2 = load_config(f.name)")
lines.append("        print(\"Reloaded config successfully\")")
lines.append("    print(\"\\n=== Config module test PASSED ===\")")

# Write file
with open("C:/Users/lenovo/hwin_net/utils/config.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Config file written successfully!")
